import fs from "fs";
import os from "os";
import path from "path";
import crypto from "crypto";

export type Shell = "zsh" | "bash" | "fish";

export const BEGIN = "# >>> git-wtree >>>";
export const END = "# <<< git-wtree <<<";

export const VERSION = ((): string => {
  try {
    const pkg = JSON.parse(
      fs.readFileSync(new URL("../../package.json", import.meta.url), "utf-8"),
    ) as { version: string };
    return pkg.version;
  } catch {
    return "0";
  }
})();

export function detectShell(explicit?: string): Shell {
  const raw = (
    explicit ?? path.basename(process.env.SHELL ?? "zsh")
  ).toLowerCase();
  if (raw.includes("fish")) return "fish";
  if (raw.includes("bash")) return "bash";
  return "zsh";
}

export function rcPathFor(shell: Shell): string {
  const home = os.homedir();
  if (shell === "fish")
    return path.join(home, ".config", "fish", "config.fish");
  if (shell === "bash") return path.join(home, ".bashrc");
  return path.join(home, ".zshrc");
}

/**
 * The generated wrapper lives here, not in the rc and not in the npm package.
 *
 * Not in the rc, so upgrading gitwtree never requires editing a file the user
 * owns. Not in the package directory either: a global npm prefix moves when you
 * switch Node versions with nvm or fnm, and this path has to be stable for the
 * rc line that points at it to keep working.
 */
export function initPathFor(shell: Shell): string {
  const ext = shell === "fish" ? "fish" : shell;
  return path.join(os.homedir(), ".config", "git-wtree", `init.${ext}`);
}

// zsh / bash wrapper. A binary cannot change its parent shell's cwd, so every
// invocation gets a temp file in GWT_CD_FILE; whatever a command writes there,
// the shell cd's to afterwards. `switch` used to be a hard-coded case here —
// making it a plain subcommand means the wrapper never needs to learn another.
//
// The leading `unalias` clears oh-my-zsh's git-plugin aliases (gwt → git worktree)
// so the function can define cleanly and win over them; harmless otherwise.
// Because this is a sourced FILE rather than a block pasted into the rc, zsh runs
// the unalias before it parses the function below it — the older inline form
// needed a nested `eval` to get the same ordering.
//
// Nothing here runs `gitwtree` at source time: the only call is `command gitwtree`
// inside the body, at run time. See docs/adr/0001.
function posixWrapper(rev: string): string {
  return `# Generated by git-wtree — do not edit; run \`gitwtree shell-init --install\`.
export GWT_SHELL_INTEGRATION=${rev}
unalias gwt gwta gwtls gwtmv gwtrm 2>/dev/null
gwt() {
  local _gwt_cd _gwt_status _gwt_dir
  _gwt_cd="$(mktemp)" || return
  GWT_CD_FILE="$_gwt_cd" command gitwtree "$@"
  _gwt_status=$?
  _gwt_dir="$(cat "$_gwt_cd" 2>/dev/null)"
  rm -f "$_gwt_cd"
  [ -n "$_gwt_dir" ] && cd "$_gwt_dir"
  return $_gwt_status
}
`;
}

function fishWrapper(rev: string): string {
  return `# Generated by git-wtree — do not edit; run \`gitwtree shell-init --install\`.
set -gx GWT_SHELL_INTEGRATION ${rev}
function gwt
  set -l _gwt_cd (mktemp)
  GWT_CD_FILE=$_gwt_cd command gitwtree $argv
  set -l _gwt_status $status
  set -l _gwt_dir (cat "$_gwt_cd" 2>/dev/null)
  rm -f "$_gwt_cd"
  test -n "$_gwt_dir"; and cd "$_gwt_dir"
  return $_gwt_status
end
`;
}

/**
 * Identifies the wrapper by its own content rather than by the package version.
 *
 * The rc used to carry the package version, so every release — even a patch that
 * touched nothing shell-side — made `doctor` report the integration as stale and
 * ask for a reinstall. A content hash only changes when the wrapper actually
 * changes, and it cannot be forgotten the way a hand-maintained counter can.
 */
export function wrapperRev(shell: Shell): string {
  const body = shell === "fish" ? fishWrapper("") : posixWrapper("");
  return crypto.createHash("sha256").update(body).digest("hex").slice(0, 8);
}

export function wrapperFor(shell: Shell): string {
  return shell === "fish"
    ? fishWrapper(wrapperRev(shell))
    : posixWrapper(wrapperRev(shell));
}

/** The line that goes in the rc. Constant for the life of the tool. */
export function loaderFor(shell: Shell): string {
  const target = initPathFor(shell).replace(os.homedir(), "$HOME");
  return shell === "fish"
    ? `test -r "${target}"; and source "${target}"`
    : `[ -r "${target}" ] && . "${target}"`;
}

/** True when the rc contains our marker block. */
export function blockPresent(rcPath: string): boolean {
  if (!fs.existsSync(rcPath)) return false;
  return fs
    .readFileSync(rcPath, "utf-8")
    .split("\n")
    .some((l) => l.startsWith(BEGIN));
}

export interface InitFileState {
  path: string;
  exists: boolean;
  /** True when the file on disk is not what this version would write. */
  stale: boolean;
}

export function initFileState(shell: Shell): InitFileState {
  const file = initPathFor(shell);
  if (!fs.existsSync(file)) return { path: file, exists: false, stale: false };
  const current = fs.readFileSync(file, "utf-8");
  return { path: file, exists: true, stale: current !== wrapperFor(shell) };
}

export function writeInitFile(shell: Shell): string {
  const file = initPathFor(shell);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, wrapperFor(shell));
  return file;
}

/**
 * Brings an ALREADY INSTALLED wrapper up to date, and does nothing otherwise.
 *
 * This is what makes an upgrade take effect without the user doing anything:
 * npm replaces the binary, the next `gwt` command rewrites the wrapper, and the
 * next terminal picks it up. It deliberately never creates the file — installing
 * shell integration is something the user opts into, not a side effect of
 * running an unrelated command.
 */
export function refreshInitFileIfInstalled(): void {
  try {
    for (const shell of ["zsh", "bash", "fish"] as const) {
      const state = initFileState(shell);
      if (state.exists && state.stale) writeInitFile(shell);
    }
  } catch {
    // Best effort: never let this break the command the user actually ran.
  }
}
